apiVersion: v1
kind: Service
metadata:
  name: samba-lb
  namespace: samba
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.4.120
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
  - name: smb
    port: 445
    targetPort: 445
    protocol: TCP
  - name: netbios
    port: 139
    targetPort: 139
    protocol: TCP