apiVersion: v1
kind: Secret
metadata:
    name: mqtt-credentials
    namespace: claudecodeui
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xLCZb1+0OIdSf4pd,iv:bWfh98yrY+d6lCPMzVyC3ty7t1nSjgD1EYoqrI9DauA=,tag:MXSEylamG2vncndau7mO0Q==,type:str]
    password: ENC[AES256_GCM,data:xlOZycu/V3sTpxPTGA==,iv:H8oSCO7mNQdXjZDnSIfqTxfRHfUyc+Gd94uUy4FVv8I=,tag:o+KeYBxvLsQHR6qOuC/C6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUWxsbFdkQUoyQjc3SHBq
            S1FxQ212c1JsVXBoYzE3WDRydVdueDJYaXd3CkRVdEsvamRKVFhMMCszbDVPd0tY
            MzJTdGNoMzRSNjBjZmJQcGI1Y3FnazQKLS0tIGhpZHozMC9rV1hXS25HWThMRGx2
            UTM1UTBQcnZRU0J5aTViaGw1RGhmQUkKa/Az2hsLDF/n0femdgIyOGi/dUh797kd
            6kagfWgjh79zFkaog4VAANPBekHD3YXIoFsOyOArlR8RCoeoe7nL3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T20:37:32Z"
    mac: ENC[AES256_GCM,data:FwaFdYCpw4b/cA6HS8VtxHEjd0Q7HkTyeCEw3ZmnjeH6K2AYclW7HSujj9m3bmL1/gpdYw3J1PQD2jE4fplv35W9tvdLnTlB4ylGSe+ra4X+ukdVWPZx+TrjmDqQccAkvKmouTaybQCfr2Z1n4r9zkayCDrF12/NVpTDv78JVoo=,iv:Z9XvAitv6QNsuXSHfiPUVazUYaQie+53F6YOabajbm0=,tag:7xbJSo/Y3qNo7rU1iaOwFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
