apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-data-blue
  namespace: claudecodeui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-projects-blue
  namespace: claudecodeui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
