apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-blue
  namespace: claudecodeui
spec:
  selector:
    app: claudecodeui-blue
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
