apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-data
  namespace: claudecodeui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-projects
  namespace: claudecodeui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
