---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: claude-sessions-smb-pv
  labels:
    usage: claude-sessions-backup
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
    - uid=1001
    - gid=1001
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle must be unique per PV
    volumeHandle: claude-sessions-smb
    volumeAttributes:
      source: "//192.168.4.120/secure/claude-sessions"
    nodeStageSecretRef:
      name: samba-credentials
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-sessions-smb
  namespace: claudecodeui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  resources:
    requests:
      storage: 10Gi
  volumeName: claude-sessions-smb-pv
