FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-buster-run

RUN pip3 install --no-cache-dir --upgrade fauxmo luma.led_matrix netifaces

COPY . /usr/src/app/

WORKDIR /usr/src/app/

CMD ["fauxmo","-c","config.json"]

