FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-buster-run


WORKDIR /usr/src/app

RUN install_packages build-essential python3-dev libfreetype6-dev libjpeg-dev libtiff5

# Defines our working directory in container
WORKDIR /usr/src/app

RUN pip3 install --no-cache-dir --upgrade luma.led_matrix netifaces

# This will copy all files in our root to the working  directory in the container
COPY . ./

# server.js will run when container starts up on the device
CMD ["python3", "./ip_display.py"]