version: '2'
services:
  frontend:
    build: ./raspberrypi-master/frontend
    ports:
      - "80:80"
  nodexporter:
    image: prom/node-exporter:master
    ports:
      - "9100:9100"
  ip_display:
    build: ./raspberrypi-master/7-segment-display
    privileged: true
    network_mode: host


