# Speak Claude responses via Google Speaker AND Voice PE
# Listens to claude/home/response and announces via TTS

alias: Claude Speak Response
description: Announces Claude Code responses via Google speaker and Voice PE
mode: queued
max: 10

trigger:
  - platform: mqtt
    topic: claude/home/response
    id: response_received

condition:
  # Trigger on simplified 'answer' messages (preferred) or result messages
  - condition: template
    value_template: "{{ '\"type\":\"answer\"' in trigger.payload or '\"type\":\"result\"' in trigger.payload }}"

action:
  # Extract the result text first
  - variables:
      result_text: >-
        {% set p = trigger.payload | from_json %}
        {% if p.type == 'answer' and p.text is defined %}
          {{ p.text | truncate(400) }}
        {% elif p.content is defined and p.content is iterable %}
          {% for item in p.content %}
            {% if item.type == 'claude-response' and item.data is defined and item.data.type == 'result' %}
              {{ item.data.result | truncate(400) }}
            {% endif %}
          {% endfor %}
        {% else %}
          Request completed
        {% endif %}
  # Run both in parallel so they don't block each other
  - parallel:
      # Google speaker (fast)
      - service: tts.speak
        target:
          entity_id: tts.piper
        data:
          media_player_entity_id: media_player.family_room_wifi
          message: "{{ result_text }}"
      # Voice PE (slow but local)
      - service: assist_satellite.announce
        target:
          entity_id: assist_satellite.home_assistant_voice_09f5a3_assist_satellite
        data:
          message: "{{ result_text }}"
