---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frigate-health-checker
  namespace: flux-system
spec:
  image: ghcr.io/homeiac/frigate-health-checker
  interval: 5m
  secretRef:
    name: ghcr-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frigate-health-checker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frigate-health-checker
  filterTags:
    # Match build-sha tags (e.g., 42-abc1234), extract build number for ordering
    pattern: '^(\d+)-[a-f0-9]{7}$'
    extract: '$1'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: frigate-health-checker
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: fluxcdbot
        email: fluxcd@homelab.local
      messageTemplate: |
        chore(flux): update frigate-health-checker image to {{range .Changed.Changes}}{{.NewValue}}{{end}}
    push:
      branch: master
  update:
    path: ./gitops/clusters/homelab/apps/frigate
    strategy: Setters
