apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: kube-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:kBqwmkq37//imNlyetysJNfeINsOqkMTskZ2hSUId5xsINdrmnzpSNjwgmvFcfQzo4lw/j1SF29tKXbZK/rvh01waWCONgfoQfL9lcS3ygqhU7gCjG2MzSoD8BwhK1RAdCI+XUA04xfd0XrxvdM1e/TEWPYuVZuKgnHwhi7hJ5SBWkTRnGR4+tqj0cixqKpw7HHiNkeoWmtETr+iw8nqBrljgc6kpKRrKKL2IQ==,iv:n+nMgmqqKjHNnik8/o+rEsoFzrtoo9/Xz1iAuz1ZPE8=,tag:lQvAuTE7mDu5cprEMBHvUw==,type:str]
sops:
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudzRDSktmSkJLdk9DUlVM
            YTFKUVZqZEsvSGdsV2Q3OVMxQjQxRnVraGhjCmRwUWZrRmF5ZzhxbGtiM00rY2M4
            eE5SZTk0a1paNEZFZWdmNXlKcmxSclkKLS0tIHY4akw1R3ZjejR0b2czL0g2SnFG
            bCtwcVFzbGliaWRnUWtQdmRNWlBOdVkKDdwNYyvPQjaV8R04kX1BWkeuJAlDiX+1
            VMGkiJXfTppx3msH4z+gxkS/iPKFh3YKTeJOmrGPzL4OgmG/Zx/+7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T19:25:20Z"
    mac: ENC[AES256_GCM,data:s53kMIE8x2VhSv3lcbNIQKTmPphssAtK86Q/25jlGQT49GA4/2IdWX550CXd947GYZFVjBN6b0N2iRVGPPVwlkX51Yu8xhzXppYfOXQR4svfRmFxhFLH+3xkPlZ80LZNFt7Oz8SwnqPohoTB3To0LE6oGF2WkMhKSRvQK1z2fnk=,iv:aNtFlYiu8QUT73xch0VAOLUW60ZTJBldPZdOobyv8Wk=,tag:CMlPWIEyuQ6rPcFd/+KWug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
