apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencloud
  namespace: opencloud
  labels:
    app: opencloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencloud
  template:
    metadata:
      labels:
        app: opencloud
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-vm-still-fawn
      hostAliases: # map domain locally to fix login errors (see issue #54)
        - ip: "127.0.0.1"
          hostnames:
            - opencloud.app.homelab
      initContainers:
        - name: init-perms
          image: busybox
          command:
            - sh
            - -c
            - |
              chown nobody:nogroup /mnt/smb_data/opencloud
              chmod 0770 /mnt/smb_data/opencloud
          volumeMounts:
            - mountPath: /mnt/smb_data/opencloud
              name: opencloud-root
      containers:
        - name: opencloud
          image: opencloudeu/opencloud-rolling:latest
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c", "opencloud init || true; opencloud server"]
          env:
            - name: OC_URL
              value: "https://opencloud.app.homelab"
            - name: OC_INSECURE
              value: "false"
            - name: PROXY_TLS
              value: "false"
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /etc/opencloud
              name: config
            - mountPath: /var/lib/opencloud
              name: data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: opencloud-config
        - name: data
          hostPath:
            path: /mnt/smb_data/opencloud/data
            type: DirectoryOrCreate
        - name: opencloud-root
          hostPath:
            path: /mnt/smb_data/opencloud
            type: DirectoryOrCreate
