apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system        # chart will create this ns
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: "0.15.2"            # latest patch in the 0.14 line
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system

