# kube-vip DaemonSet for K3s control plane HA
# https://kube-vip.io/docs/usage/k3s/
#
# IMPORTANT: Before deploying, ensure TLS-SAN is configured on all control plane nodes:
#   cd proxmox/homelab && poetry run python -m homelab.k3s_manager prepare-kube-vip
#
# This provides a floating VIP (192.168.4.79) for the K3s API server.
# The VIP moves to the leader node automatically on failover.
#
# NOTE: --services flag is NOT included because MetalLB handles LoadBalancer services.
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip
    app.kubernetes.io/component: control-plane-vip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip
    spec:
      # Only run on control plane nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      # Tolerate control plane taints
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: kube-vip
      hostNetwork: true
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.8.7
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            # VIP address for the control plane
            # Must match tls-san in K3s config and be outside MetalLB range
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: "eth0"
            - name: vip_address
              value: "192.168.4.79"
            - name: vip_cidr
              value: "24"
            # Control plane mode (not services - MetalLB handles that)
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: "kube-system"
            - name: svc_enable
              value: "false"
            # Leader election for VIP failover
            - name: vip_leaderelection
              value: "true"
            # Lease configuration
            - name: vip_leasename
              value: "kube-vip-lease"
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            # Enable prometheus metrics
            - name: prometheus_server
              value: ":2112"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
