apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-webui
  namespace: stable-diffusion
  labels:
    app: stable-diffusion-webui
spec:
  replicas: 0
  selector:
    matchLabels:
      app: stable-diffusion-webui
  template:
    metadata:
      labels:
        app: stable-diffusion-webui
    spec:
      runtimeClassName: nvidia
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: webui
          image: universonic/stable-diffusion-webui:full
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMANDLINE_ARGS
              value: "--enable-insecure-extension-access"
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /app/stable-diffusion-webui/models
              name: models
            - mountPath: /app/stable-diffusion-webui/outputs
              name: outputs
            - mountPath: /app/stable-diffusion-webui/extensions
              name: extensions
            - mountPath: /app/stable-diffusion-webui/localizations
              name: localizations
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: sd-models
        - name: outputs
          persistentVolumeClaim:
            claimName: sd-outputs
        - name: extensions
          persistentVolumeClaim:
            claimName: sd-extensions
        - name: localizations
          persistentVolumeClaim:
            claimName: sd-localizations
