apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-extensions
  namespace: stable-diffusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
