apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-localizations
  namespace: stable-diffusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
