apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-models
  namespace: stable-diffusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
