apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: crucible-virtiofs
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/crucible
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-crucible-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crucible-virtiofs
  local:
    path: /mnt/crucible/prometheus-test
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-vm-pumped-piglet-gpu
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-crucible-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crucible-virtiofs
  local:
    path: /mnt/crucible/grafana-test
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-vm-pumped-piglet-gpu
