apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-test
  namespace: monitoring-test
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "74.2.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    # Disable components we don't need for the test
    alertmanager:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    prometheusOperator:
      enabled: true
      # Use existing CRDs from main monitoring namespace
      createCustomResource: false

    prometheus:
      prometheusSpec:
        retention: 7d
        # Pin to pumped-piglet where Crucible virtiofs is mounted
        nodeSelector:
          kubernetes.io/hostname: k3s-vm-pumped-piglet-gpu
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: crucible-virtiofs
              resources:
                requests:
                  storage: 10Gi
        # Scrape same targets as main Prometheus for fair comparison
        additionalScrapeConfigs:
          - job_name: "proxmox-node-exporter"
            static_configs:
              - targets:
                  - 192.168.4.122:9100   # pve
                  - 192.168.4.17:9100    # still-fawn
                  - 192.168.4.19:9100    # chief-horse
                  - 192.168.4.172:9100   # fun-bedbug
                  - 192.168.4.175:9100   # pumped-piglet
          - job_name: "crucible-node-exporter"
            static_configs:
              - targets:
                  - 192.168.4.189:9100   # proper-raptor

    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin
        passwordKey: admin-password
      service:
        type: NodePort
        nodePort: 32090
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 2Gi
        storageClassName: crucible-virtiofs
      nodeSelector:
        kubernetes.io/hostname: k3s-vm-pumped-piglet-gpu
