apiVersion: v1
kind: ConfigMap
metadata:
  name: webtop-init-scripts
  namespace: webtop
data:
  01-setup-ssh-rdp.sh: |
    #!/bin/bash
    set -e
    
    echo "Setting up SSH and RDP services..."
    
    # Update package list and install SSH/RDP servers
    apt-get update
    apt-get install -y openssh-server xrdp
    
    # Configure SSH
    mkdir -p /var/run/sshd
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
    
    # Setup SSH key for gshiva user
    if [ ! -d /config/.ssh ]; then
      mkdir -p /config/.ssh
      chmod 700 /config/.ssh
    fi
    
    # Add your public key (replace with your actual key)
    cat > /config/.ssh/authorized_keys << 'EOF'
# Add your SSH public key here
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC... your-email@example.com
EOF
    chmod 600 /config/.ssh/authorized_keys
    
    # Configure xRDP
    echo "xfce4-session" > /etc/skel/.xsession
    sed -i 's/port=3389/port=3389/' /etc/xrdp/xrdp.ini
    
    # Start services
    service ssh start
    service xrdp start
    
    # Clean up
    apt-get clean
    rm -rf /var/lib/apt/lists/*
    
    echo "SSH and RDP setup complete!"
    echo "SSH service started on port 22"
    echo "xRDP service started on port 3389"
    echo "SSH key configured in /config/.ssh/authorized_keys"
