apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop
  namespace: webtop
  labels:
    app: webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
    spec:
      nodeSelector:
        hardware-type: nvidia-gpu
      containers:
      - name: dind
        image: docker:27-dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
        args:
        - dockerd
        - --host=tcp://127.0.0.1:2375
        - --host=unix:///var/run/docker.sock
        - --tls=false
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
      - name: webtop
        image: lscr.io/linuxserver/webtop:ubuntu-xfce
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: SUBFOLDER
          value: "/"
        - name: TITLE
          value: "Development Environment"
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2375"
        - name: CUSTOM_USER
          value: "gshiva"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: webtop-auth
              key: password
        - name: SUDO_ACCESS
          value: "true"
        - name: DOCKER_MODS
          value: "linuxserver/mods:universal-docker|linuxserver/mods:code-server-python3-poetry|linuxserver/mods:code-server-nodejs"
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3001
          name: https
        - containerPort: 22
          name: ssh
        - containerPort: 3389
          name: rdp
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "4Gi"
            cpu: "2"
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "4"
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              # Check if SSH is running
              if [ -f /usr/sbin/sshd ] && ! pgrep sshd > /dev/null; then
                exit 1
              fi
              # Check if xRDP is running  
              if [ -f /usr/sbin/xrdp ] && ! pgrep xrdp > /dev/null; then
                exit 1
              fi
              exit 0
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
        - name: dev-shm
          mountPath: /dev/shm
        - name: init-scripts
          mountPath: /custom-cont-init.d
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: webtop-config
      - name: docker-storage
        emptyDir: {}
      - name: dev-shm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      - name: init-scripts
        configMap:
          name: webtop-init-scripts
          defaultMode: 0755