apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config
  namespace: webtop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path