apiVersion: v1
kind: Service
metadata:
  name: webtop
  namespace: webtop
  labels:
    app: webtop
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 3001
    targetPort: 3001
    name: https
  selector:
    app: webtop