grafana:
  service:
    type: NodePort
    nodePort: 30080         # Access Grafana at http://<nodeIP>:30080
  adminPassword: "admin"    # Demo password; change later
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: longhorn

prometheus:
  prometheusSpec:
    # Retain 30 days of raw data (adjust as needed)
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: 100Gi
    additionalScrapeConfigs:
      - job_name: "proxmox-node-exporter"
        static_configs:
          - targets: 
              - 192.168.4.122:9100   # pve
              - 192.168.4.17:9100    # still-fawn
              - 192.168.4.19:9100    # chief-horse
              - 192.168.4.172:9100   # fun-bedbug
      - job_name: "proxmox-pve-exporter"
        metrics_path: /pve
        static_configs:
          - targets: 
              - 192.168.4.122:9221   # pve-proxmox-metrics
