{
 "title": "Traefik3",
 "description": "Traefik v2.0 dashboard Prometheus Stack",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "backend", "query": "label_values(backend)" },
   { "name": "service", "query": "label_values(service)" },
   { "name": "entrypoint", "query": "label_values(entrypoint)" },
   { "name": "code", "query": "label_values(code)" },
   { "name": "protocol", "query": "label_values(protocol)" }
  ]
 },
 "panels": [
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Traefik Backends ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(traefik_backend_server_up)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(traefik_backend_request_duration_seconds_sum[5m])) ",
     "legendFormat": "{{$backend}} | {{method}}"
    }
   ]
  },
  {
   "title": "Avergae Service response time",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(traefik_service_request_duration_seconds_sum{service=\"$service\"}[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total requests over 5min $service",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(traefik_backend_requests_total)",
     "legendFormat": "{{$backend}} | {{method}}"
    }
   ]
  },
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{backend=~\"$backend\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Entrypoint Error Codes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{backend=~\"$backend\",code!=\"200\"}[5m]) * 100",
     "legendFormat": "{{ method }} : {{code}}"
    },
    { "expr": "avg_over_time" }
   ]
  },
  {
   "title": "Requests by backend",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m])) by (backend) ",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m])) by (protocol) ",
     "legendFormat": "{{ protocol }}"
    }
   ]
  }
 ]
}