apiVersion: v1
kind: Secret
metadata:
    name: frigate-credentials
    namespace: frigate
type: Opaque
stringData:
    #ENC[AES256_GCM,data:oqIhcbsiEdR+ubdXpcpm6S9cNSgL9zBQ,iv:KTSuicWm4OkzGIvHO2PpOzGs4aSXDNDZtekQFko+RuE=,tag:aZoh+seUTKRrRJHoEjrA8A==,type:comment]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:J8l4oN3KjQ==,iv:h91I6mMGOyB6ZVMX3ueepd8payu8X0hr3fzGgsa9e0s=,tag:NdJN9DDJ2YD3t2TN56PvSA==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:2qW+0b+NpMDNkNd7rw==,iv:QL4HA5cNZym65cUc3GPbhP9j6Ok6seFZX/n5t6VUIIg=,tag:hUJvMUR9Vx9M62y16IgRzw==,type:str]
    #ENC[AES256_GCM,data:OvtuwWB9HKhfiwzht8WGXpxtvjqLurzw9sJMa8iBIhZ4i1WIZGggo2bO,iv:fsVYnYV3bIGusnP0v8Lo+6Gy6eLE4/OX7l44YytlRGw=,tag:7DJQSzXZr7mZ8vqXGQIq4A==,type:comment]
    FRIGATE_CAM_MJPEG_USER: ENC[AES256_GCM,data:uzKAL90=,iv:kRkdhE5kS6b3477EdaEFNFSLZQ3ZnevFCrqB9/mXajs=,tag:5jxsgZFt7LMGpXv5bEucvA==,type:str]
    FRIGATE_CAM_MJPEG_PASS: ENC[AES256_GCM,data:lX7Luy/j,iv:7pm2kQ8/w/teMWrzjoAS3p3RPpzFHW+mrRkG6gPJKFA=,tag:rVis6/4LHQyOoGDMnYBZTg==,type:str]
    #ENC[AES256_GCM,data:XUgW6KpHdRHpt5P84617MPUV4XxscGzNvNw2RZ3tnkCb,iv:JlQAqdrBHvQr3m3dEzuImbZNU8BYa9R7lbJfrjKx+ZI=,tag:BunCmjFG/J1C3ktqOe54/Q==,type:comment]
    FRIGATE_CAM_TRENDNET_USER: ENC[AES256_GCM,data:n1cj98I=,iv:no1sH7+w5bMQsFDV7/jHU032ULaK5awUBKuvEDHKHTc=,tag:iHDFlBjCG5ratojxfqEzog==,type:str]
    FRIGATE_CAM_TRENDNET_PASS: ENC[AES256_GCM,data:fiN4Xvi6CwDYcQ==,iv:i9cywmmwk9svf1QAYWuutHaLdgwTndG6Ew9JBiWWsTU=,tag:p714UHZ7ABBSQcGjsjfEkQ==,type:str]
    #ENC[AES256_GCM,data:ZtEvF2t/tI6cQJP1CTSu6LXvMDqJkJ2OQHBGdMG6qVys,iv:+EJcKc8D1SEv1LpYmstDUDfrymDNu5RQexip+vkNNuU=,tag:MIJX2ZO41+4UNe3eJ+Qa5Q==,type:comment]
    FRIGATE_CAM_REOLINK_USER: ENC[AES256_GCM,data:y/0TA6760w==,iv:/M5VSGZgNbbLNQLDZStJpUnjPlnQV8xgMod4+1m5YRQ=,tag:0WLTBG7n/zqp9RMMK9+kEw==,type:str]
    FRIGATE_CAM_REOLINK_PASS: ENC[AES256_GCM,data:vGF7eTmXuwEbIAC3xQ==,iv:TFfYpkhYh8i+lwJVeYSVZD6JlFYMiAnj36rvjC1NDPE=,tag:AZYL8JP13OWU4ArfjUuXTw==,type:str]
    #ENC[AES256_GCM,data:Gwtz92z33Ud0/4W9MS7vKByoRHskVUa2od/UDiUv1nnM7PMGTRk0Yg1AGUwnKewRRJWnUyI=,iv:znURSvY/vKl5T/+0Nv5axsx80hMNOCUz/AvKWS79Ico=,tag:aixdm3g5hbkbfWXdYDl05w==,type:comment]
    FRIGATE_CAM_LIVINGROOM_USER: ENC[AES256_GCM,data:PWq+noI=,iv:prAScEhN42L1NLHeQC70/soZTExmu1aEiz25wGQURko=,tag:sewBnPk0sfMlBzQpBWMDnw==,type:str]
    FRIGATE_CAM_LIVINGROOM_PASS: ENC[AES256_GCM,data:Z0BJZgRRmivUwtkTDg==,iv:d8c5B5obExuF8QF6WClSNLZrSYZsVu4zxGdWJwdeMFE=,tag:MgodRFqeah9EH/6PanOiIg==,type:str]
sops:
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc202b1FzUDhVSlV5alA3
            ZGR5ZExBWktpME9ZRUhDb3ZQVWxHeG1uWENjCmJMRU5QRXdubzdBUWg3bUVPNkxF
            YjREdFFDNmdOQWtKclltQnNMbjhQSm8KLS0tIGRqeVBDd21FL1B1VUpoLy9VeVVt
            eVBicURkREJHTzZVbDZjMHJyR0pmZ2cKLYLEDbwxUwM0Xi/oKYDGiJilv8bac+Rh
            jMxN0c7Tew5G9ri31eLHMD4Ly58ESRcLH+0KWUOMICIEm1t0NMq8sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T16:35:13Z"
    mac: ENC[AES256_GCM,data:4hn4dhqmcTpQyfKXRvriI6/aPX+vCZxubHetcyn3BPxTDLL81JAzRTlIN+Jzv3F0u2nXy9OJ/Ne/vPlqsqZy9C16NNvvQz7hQeD4tg0mDAvI4xf8inu9QjUlYYhqZhiGKUQmYnJj4TCzHipKRBpL/JkOvtxXDjOY2CD4nstphnE=,iv:L8C5RD1VJx7hQqZxwxVHyG1h34q6BWPfsCHwbtkJ05Q=,tag:cJpFNUGR+t5RxlRW9oWAnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
