apiVersion: v1
kind: Secret
metadata:
    name: sms-gateway-creds
    namespace: nut-pve
type: Opaque
stringData:
    SMS_GATEWAY_TOKEN: ENC[AES256_GCM,data:c/d06GxK8yI/RMUsdbIeiIJdC5vHAeGrIrdK8dl0mIjqxjXh,iv:J+JyLOLEEMPOgm900YeYZ/ucesHz0LvN7VkDMjKaiYw=,tag:rfKEq/RL9GMzWFPG44fEwA==,type:str]
    SMS_GATEWAY_IP: ENC[AES256_GCM,data:rgcjUaba/3IKDJvqJjo=,iv:7gcW7h6AOG7iLkgjkkuCxqNdZfoJkEuA7C+tph5PsLE=,tag:vFX0Y8cDukk+IjNxn4FT9g==,type:str]
    SMS_RECIPIENT: ENC[AES256_GCM,data:KK9wEjHXEiHYY3GW,iv:0zcQHmq9M3ArRpus3IqyuNgvtNsTS/HyuBBH3hKUZww=,tag:LpKyY3ATVHRGDRXiNxklfQ==,type:str]
    HOTSPOT_SSID: ENC[AES256_GCM,data:iqKvATpQH2OklYRO,iv:MaZMIfISoKo28ZQ5l33crb46UTLKfjR2lI1RpR9wols=,tag:5J9U0L8gaoAXGFXTvxJmzw==,type:str]
    HOTSPOT_PASSWORD: ENC[AES256_GCM,data:z1BhKRA5L4b8bA==,iv:Ff5mfII4iS62G2Fi9OKw3hLdrPXJ19D5K9fatfxKlzo=,tag:X3Pf1TTHAVrn2paARM5WPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbTlZQ2xib3lBc3l0cXR0
            Z1pBb29lV2xHdHdtVi94THgzc0RuRktrQ0NjCmZEYzU5bjEvaFE2RWhWSEdzRmNN
            Z3FpcDI5cGwwQ2FET1UvbWp6M0M2YTQKLS0tIGdESUFxTDlNR2JUd1dXUkxFc1d5
            a0VkVitJV2p6alU4SXVTZkhCazZqak0KV6obQ2NXLZOyNLBO6HKsjzuqhTqo4+9G
            cx146a2h1UjRF+xz5qrE5sH3Ea+rYT3C6o8fGOjkDB7eyrwisNsb0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T18:08:38Z"
    mac: ENC[AES256_GCM,data:GH5fEIFpFswMmWmSozTlTT7rM7bWpeKSZaEQZwT2ECDrf85eR65GMFUCMCtY5sbyXyYZmCQ5WK2P5fGLlg/bw4zLP4uVTRnYGb02Pb5UivSbIUxklctpaDke2XLYwc3bs6cPRrWAWVCwEwAI2sjVMcPxSvIZ76GWape33NbF7ZU=,iv:6egQHcZOtMZs+1qEQ6VUOnf1CH4veE6gUI3DutthiVA=,tag:BuUhqaSBqaToECNqc08Xxg==,type:str]
    version: 3.11.0
