apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-gpu
  namespace: ollama
  labels:
    app: ollama-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-gpu
  template:
    metadata:
      labels:
        app: ollama-gpu
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: ollama
          image: ollama/ollama:0.7.0
          imagePullPolicy: IfNotPresent
          args:
            - serve
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: OLLAMA_PORT
              value: "11434"
            - name: OLLAMA_GPU_OVERHEAD
              value: "1073741824"  # 1GB GPU memory overhead
            - name: OLLAMA_NUM_PARALLEL
              value: "1"  # Single parallel to reduce CPU usage
            - name: OLLAMA_MAX_LOADED_MODELS
              value: "1"  # Limit to one model to prevent memory pressure
            - name: OLLAMA_FLASH_ATTENTION
              value: "true"  # Enable flash attention for GPU efficiency
            - name: CUDA_VISIBLE_DEVICES
              value: "0"  # Explicitly use GPU 0
          ports:
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: "1"
