apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      version: "v24.9.1"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Driver is pre-installed in the VM - skip driver container
    driver:
      enabled: false
    # Toolkit configures containerd runtime
    # K3s uses a different containerd socket path
    toolkit:
      enabled: true
      env:
        - name: CONTAINERD_CONFIG
          value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
    # Device plugin exposes GPUs to k8s
    devicePlugin:
      enabled: true
    # DCGM exporter for metrics
    dcgmExporter:
      enabled: true
    # Node feature discovery for GPU detection
    nfd:
      enabled: true
    # MIG is not used (RTX 3070 doesn't support MIG)
    mig:
      strategy: single
    # Operator settings
    operator:
      defaultRuntime: containerd
    # Only run on GPU nodes
    nodeSelector:
      kubernetes.io/hostname: k3s-vm-pumped-piglet-gpu
