apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: "1.15.*"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  values:
    # Install controller and node components
    controller:
      replicas: 1
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 20Mi
    node:
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 20Mi
