apiVersion: v1
kind: Secret
metadata:
    name: samba-users
    namespace: samba
type: Opaque
stringData:
    ACCOUNT_gshiva: ENC[AES256_GCM,data:TAm3j1eS63plefuTJA==,iv:+ICzYoJU2+8U4NdNQg7ThhNd7NzzJsuWCj8v2RIDj/0=,tag:4U1uHB8sSM64csZcx9+LTQ==,type:str]
    ACCOUNT_alice: ENC[AES256_GCM,data:atX9KonzxFsDuzjrTA==,iv:P+I1Oo3XU3oX3B/11u+JJ66qlL8SeeZIlOLoYhpwdiI=,tag:VbsDRYltar6WMGEkTPy48w==,type:str]
sops:
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSFhvSWpYYURxejFhbVJz
            ZWdXVlRoQ0ZxRlpMZUovNnZxelhOUG5pVmpzClI3a3k0OGFsWC9qTG9ETXoxVWpp
            SnBTSXlWbGJVYWt2OVV5UlNDUmF1Qm8KLS0tIGlTS25ic29VZGI0dXFhcFJ2SUFx
            ejRvNVBJNkY3T0xRNEVGaFpieUZadTAKgZRsismMP2MNsItVbAgOyGrYnJrmyq4O
            /TGlnZr59FZF6aZzV0s65fvZwjGEeJB0BxSkzfCTOSvxIWxBTEY/0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T16:41:25Z"
    mac: ENC[AES256_GCM,data:eIsZ7EKpWCxG/OBG1GA6DjubHVlnJ5OldWV8ntZYeKjkKAnbbDeU7Sa8/t35VHDfyLlzut3tGgchTfaOlz2s3z6YwXgjnDLd0jp8Geq7W6t9yx9/PI6B4v6qgZUq/FRUP1UD9D52X8Tvgbq3kEmGPvrrVJVL+1164EoxUAMswZ8=,iv:AfjMRQbA3RrGQlvbGQ5MZG5k8PFL0DTq2OW/GxPfufY=,tag:2wIK5Xqu80kJNX7Z2kiLtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
