apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-alert
  namespace: monitoring
  labels:
    alertmanagerConfig: "true"
spec:
  route:
    receiver: email
  receivers:
    - name: email
      emailConfigs:
        - to: homeiac.alerts@minibloks.com
          from: homeiac.alerts@minibloks.com
          smarthost: smtppro.zoho.com:587
          authUsername: homeiac.alerts@minibloks.com
          authPassword:
            name: smtp-credentials
            key: pass
          subject: '🚨 K3s Cluster Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
          body: |
            {{ range .Alerts }}
            Alert: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Severity: {{ .Labels.severity }}
            Instance: {{ .Labels.instance }}
            Time: {{ .StartsAt }}
            {{ end }}
          tlsConfig:
            insecureSkipVerify: false