apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
# Deploy Prometheus and Grafana via Helm
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.2.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      service:
        type: NodePort
        nodePort: 30080
      adminPassword: "admin"
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        storageClassName: longhorn
    prometheus:
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-path
              resources:
                requests:
                  storage: 100Gi
        additionalScrapeConfigs:
          - job_name: "proxmox-node-exporter"
            static_configs:
              - targets:
                  - 192.168.4.122:9100
                  - 192.168.4.17:9100
                  - 192.168.4.19:9100
                  - 192.168.4.172:9100
          - job_name: "proxmox-pve-exporter"
            metrics_path: /pve
            static_configs:
              - targets:
                  - 192.168.4.122:9221
