apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
# Deploy Prometheus and Grafana via Helm
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "74.2.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
      valuesKey: values.yaml
