apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-secret
  namespace: monitoring
type: Opaque
stringData:
  smtp-password: "REPLACE_WITH_GMAIL_APP_PASSWORD"  # See instructions below

---
# THIS FILE IS FOR REFERENCE ONLY - NOT DEPLOYED BY FLUX
# This file is kept in git for documentation but excluded from kustomization.yaml
#
# MANUAL SETUP INSTRUCTIONS FOR EMAIL ALERTING:
#
# 1. Choose your email provider and enable 2FA:
#    GMAIL:
#    - Go to https://myaccount.google.com/security
#    - Enable "2-Step Verification"
#    - Go to https://myaccount.google.com/apppasswords
#    - Generate app password for "Mail" → "Kubernetes Alertmanager"
#    - Copy the 16-character password (remove spaces)
#
#    YAHOO (Alternative):
#    - Go to Yahoo Account Security settings
#    - Enable 2-step verification if required
#    - Generate app password for mail applications
#
# 2. Update monitoring-values.yaml:
#    - Replace "your-email@gmail.com" with your actual email address
#    - For Yahoo: change smtp_smarthost to 'smtp.mail.yahoo.com:587'
#
# 3. Create the secret manually in your cluster:
#    kubectl create secret generic alertmanager-smtp-secret \
#      --from-literal=smtp-password='YOUR_16_CHAR_APP_PASSWORD' \
#      -n monitoring
#
# 4. Verify the secret exists:
#    kubectl get secret alertmanager-smtp-secret -n monitoring
#
# 5. Test alerting (optional):
#    kubectl patch prometheusrule k3s-cpu-alerts -n monitoring --type='merge' \
#      -p='{"spec":{"groups":[{"name":"k3s-node-cpu","rules":[{"alert":"TestAlert","expr":"up","for":"0s","labels":{"severity":"critical"},"annotations":{"summary":"Test alert"}}]}]}}'
#
# SECURITY NOTE: Never commit real passwords to git!