#!/bin/bash
# 02-print-opnsense-dns-fix-steps.sh
# Prints manual steps to fix DNS in OPNsense
# No automated changes - user applies these manually

echo "========================================="
echo "OPNsense DNS Fix Steps (Option B)"
echo "========================================="
echo ""
echo "Use this fix when MAAS DNS forwarding to OPNsense is not working."
echo ""
echo "========================================="
echo "Step 1: Access OPNsense Web UI"
echo "========================================="
echo ""
echo "  URL: https://192.168.4.1"
echo "  Login with your OPNsense credentials"
echo ""
echo "========================================="
echo "Step 2: Navigate to DNS Overrides"
echo "========================================="
echo ""
echo "  Services -> Unbound DNS -> Overrides"
echo "  Click on 'Host Overrides' tab"
echo ""
echo "========================================="
echo "Step 3: Verify/Add Wildcard Override"
echo "========================================="
echo ""
echo "  Look for an existing entry with:"
echo "    Host: *"
echo "    Domain: app.homelab"
echo "    IP: 192.168.4.80"
echo ""
echo "  If it doesn't exist, click '+' to add:"
echo "    Host: *"
echo "    Domain: app.homelab"
echo "    Type: A"
echo "    IP: 192.168.4.80"
echo "    Description: Wildcard for Traefik ingress"
echo ""
echo "========================================="
echo "Step 4: Apply Changes"
echo "========================================="
echo ""
echo "  Click 'Save'"
echo "  Click 'Apply' at the top of the page"
echo ""
echo "========================================="
echo "Step 5: Reboot OPNsense (if needed)"
echo "========================================="
echo ""
echo "  If changes don't take effect:"
echo "    System -> Reboot"
echo ""
echo "  This is a known quirk - host overrides sometimes"
echo "  only apply after a full reboot."
echo ""
echo "========================================="
echo "Step 6: Verify"
echo "========================================="
echo ""
echo "  Run: ./04-verify-frigate-app-homelab-works.sh"
echo "  Or manually: dig frigate.app.homelab @192.168.4.1 +short"
echo "  Expected: 192.168.4.80"
echo ""
