#!/bin/bash
# 03-print-ha-nmcli-fix-commands.sh
# Prints nmcli commands to run on Home Assistant console
# No automated changes - user runs these manually

echo "========================================="
echo "Home Assistant nmcli Fix Commands (Option C)"
echo "========================================="
echo ""
echo "Use this fix to set OPNsense (192.168.4.1) as HA's DNS server."
echo "Requires console access to Home Assistant OS."
echo ""
echo "========================================="
echo "Step 1: Access HA Console"
echo "========================================="
echo ""
echo "  Option A: Terminal & SSH Add-on"
echo "    - Install from Settings -> Add-ons -> Terminal & SSH"
echo "    - Open Web UI and type: login"
echo ""
echo "  Option B: Proxmox Console"
echo "    - Proxmox -> VM 103 (homeassistant) -> Console"
echo "    - Login as 'root' (if enabled) or use recovery"
echo ""
echo "========================================="
echo "Step 2: Check Current DNS Configuration"
echo "========================================="
echo ""
echo "  Run these commands on HA console:"
echo ""
echo "    # List network connections"
echo "    nmcli connection show"
echo ""
echo "    # Check DNS for main interface (usually Supervisor enp0s18)"
echo "    nmcli connection show \"Supervisor enp0s18\" | grep dns"
echo ""
echo "========================================="
echo "Step 3: Set OPNsense as DNS Server"
echo "========================================="
echo ""
echo "    # Set OPNsense (192.168.4.1) as DNS"
echo "    nmcli connection modify \"Supervisor enp0s18\" ipv4.dns \"192.168.4.1\""
echo ""
echo "========================================="
echo "Step 4: Apply Changes"
echo "========================================="
echo ""
echo "    # Reload NetworkManager configuration"
echo "    nmcli connection reload"
echo ""
echo "    # Restart the connection"
echo "    nmcli connection up \"Supervisor enp0s18\""
echo ""
echo "========================================="
echo "Step 5: Verify DNS Works"
echo "========================================="
echo ""
echo "    # Test DNS resolution"
echo "    nslookup frigate.app.homelab"
echo ""
echo "    # Expected output:"
echo "    # Server:    192.168.4.1"
echo "    # Address:   192.168.4.1#53"
echo "    # Name:      frigate.app.homelab"
echo "    # Address:   192.168.4.80"
echo ""
echo "========================================="
echo "Rollback (if needed)"
echo "========================================="
echo ""
echo "    # Remove custom DNS setting"
echo "    nmcli connection modify \"Supervisor enp0s18\" ipv4.dns \"\""
echo "    nmcli connection reload"
echo "    nmcli connection up \"Supervisor enp0s18\""
echo ""
echo "========================================="
echo "Note: Interface Name"
echo "========================================="
echo ""
echo "  The interface 'Supervisor enp0s18' is typical for HA OS."
echo "  Check your actual interface name with: nmcli connection show"
echo "  It might be different (e.g., eth0, enp0s19, etc.)"
echo ""
