#!/bin/bash
# deploy.sh - Orchestrator for deploying NUT to Proxmox host
# Runs in K8s Job, deploys scripts/configs to pve via SSH/SCP
#
# Environment variables:
#   TARGET_HOST       - Proxmox host IP (required)
#   SSH_KEY_PATH      - Path to SSH private key (default: /ssh/id_rsa)
#   DEPLOY_DIR        - Target directory on host (default: /opt/nut)
#   SMS_GATEWAY_IP    - SMS gateway IP for notifications
#   SMS_GATEWAY_PORT  - SMS gateway port (default: 8082)
#   SMS_GATEWAY_TOKEN - SMS gateway auth token
#   SMS_RECIPIENT     - Phone number for SMS alerts
#   HOTSPOT_SSID      - WiFi fallback hotspot SSID
#   HOTSPOT_PASSWORD  - WiFi fallback hotspot password

set -e

HOST="${TARGET_HOST:?TARGET_HOST environment variable required}"
SSH_KEY="${SSH_KEY_PATH:-/ssh/id_rsa}"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/nut}"
SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -i $SSH_KEY"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"; }

log "Starting NUT deployment to $HOST"
log "Deploy directory: $DEPLOY_DIR"

# Test SSH connectivity
if ! ssh $SSH_OPTS root@$HOST "hostname" >/dev/null 2>&1; then
    log "ERROR: Cannot SSH to $HOST"
    exit 1
fi
log "SSH connectivity OK"

# Create deploy directories on host
log "Creating deployment directories..."
ssh $SSH_OPTS root@$HOST "mkdir -p $DEPLOY_DIR/{scripts,configs}"

# Deploy NUT configs to /etc/nut
log "Deploying NUT configuration files to /etc/nut..."
ssh $SSH_OPTS root@$HOST "dpkg -l | grep -q '^ii.*nut ' || (apt-get update && apt-get install -y nut nut-client nut-server)"
for conf in /app/configs/*.conf; do
    if [[ -f "$conf" ]]; then
        filename=$(basename "$conf")
        scp $SSH_OPTS "$conf" "root@$HOST:/etc/nut/$filename"
        log "  Deployed /etc/nut/$filename"
    fi
done

# Deploy upsd.users (not a .conf file)
if [[ -f "/app/configs/upsd.users" ]]; then
    scp $SSH_OPTS "/app/configs/upsd.users" "root@$HOST:/etc/nut/upsd.users"
    log "  Deployed /etc/nut/upsd.users"
fi

# Set permissions on sensitive NUT files
ssh $SSH_OPTS root@$HOST "chmod 640 /etc/nut/upsd.users /etc/nut/upsmon.conf && chown root:nut /etc/nut/upsd.users /etc/nut/upsmon.conf"

# Deploy scripts to $DEPLOY_DIR/scripts
log "Deploying scripts to $DEPLOY_DIR/scripts..."
for script in /app/scripts/*.sh; do
    if [[ -f "$script" ]]; then
        filename=$(basename "$script")
        scp $SSH_OPTS "$script" "root@$HOST:$DEPLOY_DIR/scripts/$filename"
        ssh $SSH_OPTS root@$HOST "chmod +x $DEPLOY_DIR/scripts/$filename"
        log "  Deployed $DEPLOY_DIR/scripts/$filename"
    fi
done

# Create symlink for nut-notify.sh in /root (required by upsmon.conf)
ssh $SSH_OPTS root@$HOST "ln -sf $DEPLOY_DIR/scripts/nut-notify.sh /root/nut-notify.sh"
log "  Created symlink /root/nut-notify.sh -> $DEPLOY_DIR/scripts/nut-notify.sh"

# Deploy secrets as .env file
log "Deploying secrets to $DEPLOY_DIR/.env..."
ssh $SSH_OPTS root@$HOST "cat > $DEPLOY_DIR/.env << 'ENVEOF'
# Auto-generated by deploy job - do not edit manually
# Secrets managed via K8s Secret -> deployed here
SMS_GATEWAY_IP=${SMS_GATEWAY_IP:-}
SMS_GATEWAY_PORT=${SMS_GATEWAY_PORT:-8082}
SMS_GATEWAY_TOKEN=${SMS_GATEWAY_TOKEN:-}
SMS_RECIPIENT=${SMS_RECIPIENT:-}
ENVEOF
chmod 600 $DEPLOY_DIR/.env"
log "  Deployed $DEPLOY_DIR/.env (mode 600)"

# Configure WiFi fallback hotspot if credentials provided
if [[ -n "${HOTSPOT_SSID:-}" ]] && [[ -n "${HOTSPOT_PASSWORD:-}" ]]; then
    log "Configuring WiFi fallback hotspot - ${HOTSPOT_SSID}"
    ssh $SSH_OPTS root@$HOST "printf '%s\n' '[Security]' 'Passphrase=${HOTSPOT_PASSWORD}' \
        > '/var/lib/iwd/${HOTSPOT_SSID}.psk' && chmod 600 '/var/lib/iwd/${HOTSPOT_SSID}.psk'"
    log "  Deployed iwd config for ${HOTSPOT_SSID}"
else
    log "  Skipping WiFi fallback (HOTSPOT_SSID/HOTSPOT_PASSWORD not set)"
fi

# Setup local crons on host
log "Setting up local crons..."
ssh $SSH_OPTS root@$HOST "cat > /etc/cron.d/nut-disaster-drill << 'CRONEOF'
# Monthly disaster drill - first Saturday of each month at 10:00 AM
# Schedule: minute hour day-of-month month day-of-week user command
# This runs on days 1-7 (first week) but only on Saturday (day 6)
0 10 1-7 * 6 root [ \$(date +\\%u) -eq 6 ] && $DEPLOY_DIR/scripts/disaster-drill.sh >> /var/log/nut-disaster-drill.log 2>&1
CRONEOF
chmod 644 /etc/cron.d/nut-disaster-drill"
log "  Created /etc/cron.d/nut-disaster-drill"

# Setup udev rules for CyberPower UPS
log "Setting up udev rules..."
ssh $SSH_OPTS root@$HOST 'cat > /etc/udev/rules.d/90-nut-ups.rules << EOF
# CyberPower UPS - allow nut user access
SUBSYSTEM=="usb", ATTR{idVendor}=="0764", MODE="0664", GROUP="nut"
EOF
udevadm control --reload-rules && udevadm trigger'

# Install nut_exporter if not present
log "Ensuring nut_exporter is installed..."
ssh $SSH_OPTS root@$HOST '
if ! [[ -f /usr/local/bin/nut_exporter ]]; then
    echo "Installing nut_exporter v3.2.2..."
    curl -sL -o /usr/local/bin/nut_exporter https://github.com/DRuggeri/nut_exporter/releases/download/v3.2.2/nut_exporter-v3.2.2-linux-amd64
    chmod +x /usr/local/bin/nut_exporter
    echo "nut_exporter installed"
else
    echo "nut_exporter already installed"
fi
'

# Create systemd service for nut_exporter
log "Configuring nut_exporter systemd service..."
ssh $SSH_OPTS root@$HOST 'cat > /etc/systemd/system/nut_exporter.service << EOF
[Unit]
Description=NUT Exporter for Prometheus
After=network.target nut-server.service

[Service]
Type=simple
ExecStart=/usr/local/bin/nut_exporter --nut.server=127.0.0.1 --web.listen-address=:9199
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
'

# Enable and start services
log "Enabling and starting services..."
ssh $SSH_OPTS root@$HOST '
systemctl daemon-reload
systemctl enable nut-server nut-monitor nut_exporter
systemctl restart nut-server
sleep 2
systemctl restart nut-monitor
systemctl restart nut_exporter
'

# Verify UPS connection
log "Verifying UPS connection..."
sleep 3
if ssh $SSH_OPTS root@$HOST "upsc ups@localhost battery.charge" 2>/dev/null; then
    CHARGE=$(ssh $SSH_OPTS root@$HOST "upsc ups@localhost battery.charge 2>/dev/null")
    log "UPS detected! Battery charge: ${CHARGE}%"
else
    log "WARNING: UPS not detected. Check USB connection."
fi

# Verify nut_exporter
log "Verifying nut_exporter..."
if ssh $SSH_OPTS root@$HOST "curl -s http://localhost:9199/metrics | grep -q nut_battery_charge"; then
    log "nut_exporter is serving metrics"
else
    log "WARNING: nut_exporter metrics not available yet"
fi

# Check service status
log "Service status:"
ssh $SSH_OPTS root@$HOST '
for svc in nut-server nut-monitor nut_exporter; do
    status=$(systemctl is-active $svc 2>/dev/null || echo "inactive")
    echo "  $svc: $status"
done
'

log "========================================"
log "Deployment complete!"
log "Scripts deployed to: $DEPLOY_DIR/scripts/"
log "Configs deployed to: /etc/nut/"
log "Secrets deployed to: $DEPLOY_DIR/.env"
log "Crons deployed to: /etc/cron.d/nut-disaster-drill"
log "========================================"
