apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: ollama
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zlRqVDMP9CN6cCZDkNWOOYD+00ozRPsiM2yln99l5Znyj4O0Wcad9rMf9WW+Y+Cl/Nkac1m9JeLwzatlwP9A2stGQMow67EDXflx1XWdmI8mZpyonhRk3qM6n3uSXKvceOd4FpQtMgsgsoaqo/AvYT4bi7LNL9yyarcgMEwXHJetTNs7wZILMmoJLFoZ9VxtAInMJGXlJviNXisMCDLUT7g2ZnMHWMK6vlg0qg==,iv:aukokOBL3IHL6JqFKxKLhKTvMFRt57GCKd5WhwJdi/k=,tag:Qtamug5yONtPFLshhHZDzA==,type:str]
sops:
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySVNoTFNqZVJQMUE1d0hZ
            ckZ5aXdDb3pOSDNWL3BpQjloc2RiS1BxU2dZCko5RysyUDE5NU53ejZ6Yi9ocU9L
            MUt2emhVK0ZOdmxnU2hyMm9wdWVtUFEKLS0tIEcxcCsvRUFiSmthdVQ5a0dYazRm
            YXFRYVBUMUdoeGNtWHhJUjFXenRiTWMKK8XMVKycTOqG4SC+2nF8SxzDKZI0xWnY
            aPiAhlCcetAQEFEw62G+sPaFIVjOD1wxJzct73de+0y1QiegX+DDmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T19:13:42Z"
    mac: ENC[AES256_GCM,data:5Smqq98kT8GdUExFilAWJ3QBkldTRn9pABqHkfMAQQK+fApRfwG2bOZVRFkN/Fn5BkXLAN23wx2CSMpQyRPereQfOlIQd9cuXOiSNvLC9RdP+jqRyXbQzVbZhrDvvKO/Y3bL6N8d14sjazx9X1Zd85S16NlGuknRHg7GGJ9eR6o=,iv:ZM0Pd+DTqnSmRyK+ig45txZ8igNI8GxrU1NX5qwnGyY=,tag:6kIgIUNH+c8Vs61y54Z1Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
