# K3s Cluster Join Token
# This secret stores the token used to join new nodes to the K3s cluster
#
# The token is read by scripts/k3s/join-server.sh
# To get the token: ssh to control-plane, cat /var/lib/rancher/k3s/server/node-token
#
# IMPORTANT: This file should be SOPS encrypted before committing
# Run: sops -e -i gitops/clusters/homelab/instances/k3s-join-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: k3s-join-token
    namespace: crossplane-system
    labels:
        purpose: k3s-cluster-join
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:CgZAHzfq3V0No18Ac7S+hGfOgR+rGFUcGDrECu22GlnQ8Ja6ffaldkZ3se9WZuYqPxxWk3l6rCdy9xwJQsl75ovhsRCRL+dLblv3Q+DkEurr1eWhg7XxLxKjsczc9/6zQCCWaDrnDVk2aFy7,iv:/IJiRJOYM5kAUrWX8dqJsnV+kz3EgLstU1+Z49QABMQ=,tag:rCbKUdmLe3WA31Y80kxWvg==,type:str]
sops:
    age:
        - recipient: age1uwvq3llqjt666t4ckls9wv44wcpxxwlu8svqwx5kc7v76hncj94qg3tsna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RjBVWnV0MmE3bEFVaDBM
            WlE5NHlyb3V2TVFDVDA0bDJ2T0NOQTdlemw4CkxxZWY1Y3F2NDk1Ti9mZVl1SjMz
            RkIxY0VDSTdoMm1hVUhLSDVGWVJrb2sKLS0tIHYwVkwvUjgzRStqOFpZQWVFNUhN
            eTQxNmlwOURmZitjbDN3SmRGV1hiaXMKxlUt9dleqLZYgS/E6+ug7vbRCKa1xVEf
            ny5n3wPNcWb7d+mtO01K+R6kMefe6x5TAV12hyiHUaAqnveCHfdZfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T19:06:21Z"
    mac: ENC[AES256_GCM,data:YRSLj5rfOylmuQUucSENR1u5yx9rRxqHvGmyEkCG6e//OuYK8EQA7tg/o1vzGaR/NztUsKP3765i4GkDBE9SAZNF6fRm8SwJrtDsRVcH1MWuU1+Q1WKUOeLdIDYOauJSLgflACH1QzppQvGrpSlLTmZI51yZ3pF5b3/B+s6Ok74=,iv:uC8H84EzhW+dF3Gf0romuJTFnbRO57c4Uz8+TC41h1Y=,tag:v2+R8EkqE8aLtknbcbfDLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
