# K3s control-plane node on fun-bedbug
# Purpose: Restore 3-node etcd quorum after still-fawn removal
# Created: 2026-01-16
# STOPPED: 2026-01-18 - Thermal issues on ATOPNUC MA90 (90째C+), running 2-node cluster
#
# IMPORTANT: fun-bedbug only has 'local' directory storage active
# ZFS pools are DISABLED on this host - do not use local-zfs
#
# DEPENDENCY: Requires EnvironmentDownloadFile 'ubuntu-noble-cloud-image'
# to be synced first (see ubuntu-noble-cloud-image.yaml)
---
apiVersion: virtualenvironmentvm.crossplane.io/v1alpha1
kind: EnvironmentVM
metadata:
  name: k3s-vm-fun-bedbug
  labels:
    role: k3s-control-plane
    node: fun-bedbug
    managed-by: crossplane
spec:
  forProvider:
    nodeName: fun-bedbug
    name: k3s-vm-fun-bedbug
    vmId: 114
    description: "K3s control-plane node - Crossplane managed"

    # Disabled 2026-01-25 - thermal issues (91째C under load)
    # Using 3-node cluster: pumped-piglet, still-fawn, pve (standby)
    started: false
    onBoot: false

    # Machine configuration - i440fx for simplicity (no GPU passthrough needed)
    machine: pc-i440fx-8.1
    bios: seabios

    # CPU: Minimal for AMD A9-9400 (2-core low-power APU)
    # Reduced to 1 core - this VM is quorum-only (no workloads)
    # 2 cores caused thermal throttling (92째C+ on 70째C high threshold)
    cpu:
      - cores: 1
        type: host

    # Memory: 4GB matches other control-plane nodes
    memory:
      - dedicated: 4096

    # SCSI Controller
    scsiHardware: virtio-scsi-pci

    # Boot disk - import cloud image directly into disk
    # IMPORTANT: importFrom must reference a file in 'import' content type
    # The EnvironmentDownloadFile creates: local:import/noble-server-cloudimg-amd64.qcow2
    disk:
      - interface: scsi0
        datastoreId: local
        size: 50
        fileFormat: raw
        discard: "on"
        importFrom: local:import/noble-server-cloudimg-amd64.qcow2

    # Network - single NIC on main bridge
    networkDevice:
      - bridge: vmbr0
        model: virtio
        enabled: true

    # Cloud-init configuration
    initialization:
      - datastoreId: local
        userAccount:
          - username: ubuntu
        ipConfig:
          - ipv4:
              - address: dhcp
        # Full K3s cloud-init - prepares VM AND joins cluster automatically
        # Snippet deployed via: scp scripts/k3s/snippets/k3s-server-fun-bedbug.yaml root@fun-bedbug.maas:/var/lib/vz/snippets/
        userDataFileId: local:snippets/k3s-server-fun-bedbug.yaml

    # QEMU Guest Agent - required for proper shutdown/status
    agent:
      - enabled: true
        trim: true
        type: virtio

  # Provider configuration reference
  providerConfigRef:
    name: default

  # IMPORTANT: Orphan policy means deleting CR won't delete VM
  # Use Orphan during initial deployment for safety
  deletionPolicy: Orphan
