# K3s control-plane node on fun-bedbug
# Purpose: Restore 3-node etcd quorum after still-fawn removal
# Created: 2026-01-16
#
# IMPORTANT: fun-bedbug only has 'local' directory storage active
# ZFS pools are DISABLED on this host - do not use local-zfs
#
# DEPENDENCY: Requires EnvironmentDownloadFile 'ubuntu-noble-cloud-image'
# to be synced first (see ubuntu-noble-cloud-image.yaml)
---
apiVersion: virtualenvironmentvm.crossplane.io/v1alpha1
kind: EnvironmentVM
metadata:
  name: k3s-vm-fun-bedbug
  labels:
    role: k3s-control-plane
    node: fun-bedbug
    managed-by: crossplane
spec:
  forProvider:
    nodeName: fun-bedbug
    name: k3s-vm-fun-bedbug
    vmId: 114
    description: "K3s control-plane node - Crossplane managed"

    # CRITICAL: Must be true for VM to start after creation
    started: true
    onBoot: true

    # Machine configuration - i440fx for simplicity (no GPU passthrough needed)
    machine: pc-i440fx-8.1
    bios: seabios

    # CPU: Conservative for AMD A9-9400 (2-core low-power APU)
    cpu:
      - cores: 2
        type: host

    # Memory: 4GB matches other control-plane nodes
    memory:
      - dedicated: 4096

    # SCSI Controller
    scsiHardware: virtio-scsi-pci

    # Boot disk - import cloud image directly into disk
    # IMPORTANT: importFrom must reference a file in 'import' content type
    # The EnvironmentDownloadFile creates: local:import/noble-server-cloudimg-amd64.qcow2
    disk:
      - interface: scsi0
        datastoreId: local
        size: 50
        fileFormat: raw
        discard: "on"
        importFrom: local:import/noble-server-cloudimg-amd64.qcow2

    # Network - single NIC on main bridge
    networkDevice:
      - bridge: vmbr0
        model: virtio
        enabled: true

    # Cloud-init configuration
    initialization:
      - datastoreId: local
        userAccount:
          - username: ubuntu
        ipConfig:
          - ipv4:
              - address: dhcp
        # Custom cloud-init with K3s prerequisites and qemu-guest-agent
        # NOTE: This snippet prepares the VM but does NOT install K3s
        # Run scripts/k3s/join-server.sh <VM_IP> after VM boots to join cluster
        userDataFileId: local:snippets/k3s-vm-prep.yaml

    # QEMU Guest Agent - required for proper shutdown/status
    agent:
      - enabled: true
        trim: true
        type: virtio

  # Provider configuration reference
  providerConfigRef:
    name: default

  # IMPORTANT: Orphan policy means deleting CR won't delete VM
  # Use Orphan during initial deployment for safety
  deletionPolicy: Orphan
