# K3s control-plane node on still-fawn
# Purpose: GPU-accelerated K3s node for Frigate (VAAPI) and Coral TPU
# Created: 2026-01-17
#
# Hardware passthrough (added via post-create Job - API token lacks perms):
# - AMD Radeon RX 570/580 (PCI 01:00) - VAAPI encoding for Frigate
# - Google Coral USB TPU (1a6e:089a, 18d1:9302) - Object detection
#
# DEPENDENCIES:
# 1. Cloud image: EnvironmentDownloadFile 'ubuntu-noble-cloud-image-still-fawn'
# 2. Cloud-init snippet: scripts/k3s/snippets/k3s-server-still-fawn.yaml
#    Deploy with: ./scripts/k3s/deploy-snippets.sh still-fawn
# 3. Passthrough Job: After VM created, run job-vm108-passthrough.yaml
---
apiVersion: virtualenvironmentvm.crossplane.io/v1alpha1
kind: EnvironmentVM
metadata:
  name: k3s-vm-still-fawn
  labels:
    role: k3s-control-plane
    node: still-fawn
    managed-by: crossplane
    gpu: amd-vaapi
    tpu: coral-usb
spec:
  forProvider:
    nodeName: still-fawn
    name: k3s-vm-still-fawn
    vmId: 108
    description: "K3s node with AMD GPU (VAAPI) + Coral TPU - Crossplane managed"

    # CRITICAL: Start as false - passthrough job will start after adding devices
    started: false
    onBoot: true

    # Machine configuration - q35 required for PCI passthrough
    machine: q35
    bios: seabios

    # CPU: All 4 cores of i5-4460 (no hyperthreading)
    cpu:
      - cores: 4
        type: host

    # Memory: 25GB for K3s workloads (Frigate, monitoring, etc.)
    memory:
      - dedicated: 25600

    # SCSI Controller
    scsiHardware: virtio-scsi-pci

    # Boot disk - import cloud image, 700GB on local-zfs
    disk:
      - interface: scsi0
        datastoreId: local-zfs
        size: 700
        fileFormat: raw
        cache: writeback
        iothread: true
        discard: "on"
        importFrom: local:import/noble-server-cloudimg-amd64.qcow2

    # Network - single NIC on main bridge (preserve MAC for DHCP lease)
    networkDevice:
      - bridge: vmbr0
        model: virtio
        macAddress: "BC:24:11:90:21:DF"
        enabled: true

    # NOTE: USB and PCI passthrough added via post-create Job
    # Crossplane API token lacks Mapping.Use permission for real devices

    # Serial console for cloud-init and debugging
    serialDevice:
      - device: socket

    # Cloud-init configuration
    initialization:
      - datastoreId: local-zfs
        userAccount:
          - username: ubuntu
        ipConfig:
          - ipv4:
              - address: dhcp
        # Host-specific cloud-init with correct hostname
        userDataFileId: local:snippets/k3s-server-still-fawn.yaml

    # QEMU Guest Agent - required for proper shutdown/status
    agent:
      - enabled: true
        trim: true
        type: virtio

  # Provider configuration reference
  providerConfigRef:
    name: default

  # IMPORTANT: Orphan policy means deleting CR won't delete VM
  deletionPolicy: Orphan
