# Rancher Server VM - RKE2 control plane + Rancher UI
# VMID 200 on pumped-piglet - ADOPTING EXISTING VM
---
apiVersion: virtualenvironmentvm.crossplane.io/v1alpha1
kind: EnvironmentVM
metadata:
  name: rancher-server
  annotations:
    # Adopt existing VM instead of creating new one
    crossplane.io/external-name: "200"
  labels:
    app: rancher
    environment: eval
    managed-by: crossplane
spec:
  forProvider:
    nodeName: pumped-piglet
    vmId: 200
    name: rancher-server
    description: "RKE2 control plane + Rancher UI (Crossplane-managed)"

    # CPU configuration
    cpu:
      - cores: 4
        type: host

    # Memory (8GB)
    memory:
      - dedicated: 8192

    # Boot disk - 100GB on local ZFS
    disk:
      - interface: scsi0
        datastoreId: local-2TB-zfs
        size: 100
        discard: "on"
        iothread: true
        cache: writeback

    # Network on vmbr0 (192.168.4.x)
    networkDevice:
      - bridge: vmbr0
        model: virtio

    # Cloud-init configuration
    initialization:
      - datastoreId: local-2TB-zfs
        userAccount:
          - username: ubuntu
            # SSH keys from Proxmox host
        ipConfig:
          - ipv4:
              - address: "192.168.4.200/24"
                gateway: "192.168.4.1"
        dns:
          - servers:
              - "192.168.4.1"

    # Enable QEMU guest agent
    agent:
      - enabled: true

    # VM behavior
    onBoot: true
    started: true

  # Use the default ProviderConfig
  providerConfigRef:
    name: default
