# Ubuntu Noble (24.04) cloud image for VM import
# Downloaded via Crossplane/Terraform bpg provider
# Required: storage must have 'import' content type enabled
---
apiVersion: virtualenvironmentdownloadfile.crossplane.io/v1alpha1
kind: EnvironmentDownloadFile
metadata:
  name: ubuntu-noble-cloud-image
  labels:
    managed-by: crossplane
    image-type: cloud-init
spec:
  forProvider:
    nodeName: fun-bedbug
    datastoreId: local
    contentType: import
    url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    # IMPORTANT: Must use .qcow2 extension for import content type
    fileName: noble-server-cloudimg-amd64.qcow2
    # Adopt existing file if present (avoids "refusing to override" error)
    overwriteUnmanaged: true
  providerConfigRef:
    name: default
  deletionPolicy: Orphan
