# Ubuntu Noble (24.04) cloud image for VM import on pve host
# Downloaded via Crossplane/Terraform bpg provider
# Required: storage must have 'import' content type enabled
#
# NOTE: pve host requires .img extension (Proxmox version/storage config difference)
---
apiVersion: virtualenvironmentdownloadfile.crossplane.io/v1alpha1
kind: EnvironmentDownloadFile
metadata:
  name: ubuntu-noble-cloud-image-pve
  labels:
    managed-by: crossplane
    image-type: cloud-init
    target-host: pve
spec:
  forProvider:
    nodeName: pve
    datastoreId: local
    contentType: import
    url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    # pve requires .img extension (not .qcow2 like other nodes)
    fileName: noble-server-cloudimg-amd64.img
    overwriteUnmanaged: true
  providerConfigRef:
    name: default
  deletionPolicy: Orphan
