#!/bin/bash
# Generate README.md files for script directories
# Usage: ./scripts/generate-readme.sh [directory...]
# If no directories specified, generates for all scripts/* directories

set -e

generate_readme() {
    local dir="$1"
    local readme="$dir/README.md"
    local dir_name=$(basename "$dir")

    # Skip archive and lib directories
    [[ "$dir_name" == "archive" || "$dir_name" == "lib-sh" ]] && return

    # Count scripts
    local count=$(ls "$dir"/*.sh 2>/dev/null | wc -l | tr -d ' ')
    [[ "$count" == "0" ]] && return

    echo "Generating $readme ($count scripts)..."

    cat > "$readme" << EOF
# $dir_name Scripts

> Auto-generated by \`scripts/generate-readme.sh\` - do not edit manually

## Scripts

| Script | Description |
|--------|-------------|
EOF

    for f in "$dir"/*.sh; do
        [[ -f "$f" ]] || continue
        local name=$(basename "$f")
        # Extract first comment line (line 2, after shebang)
        local desc=$(sed -n '2s/^#[[:space:]]*//p' "$f" | head -1)
        [[ -z "$desc" ]] && desc="*(no description)*"
        echo "| \`$name\` | $desc |" >> "$readme"
    done

    # Add usage section if lib-sh exists
    if [[ -f "$dir/../lib-sh/ha-api.sh" && "$dir_name" == "haos" ]]; then
        cat >> "$readme" << 'EOF'

## Library

These scripts use the shared library at `scripts/lib-sh/ha-api.sh`.

To create a new script:
```bash
#!/bin/bash
# Description of what this script does
source "$(dirname "$0")/../lib-sh/ha-api.sh"

# Use library functions:
# ha_get_state "sensor.temperature"
# ha_call_service "light" "turn_on" '{"entity_id": "light.kitchen"}'
# ha_api_get "config"
# ha_api_post "services/script/reload" "{}"
```
EOF
    fi

    echo "" >> "$readme"
    echo "*Generated: $(date '+%Y-%m-%d')*" >> "$readme"
}

# Main
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -gt 0 ]]; then
    # Generate for specified directories
    for dir in "$@"; do
        [[ -d "$dir" ]] && generate_readme "$dir"
    done
else
    # Generate for all script directories
    for dir in "$SCRIPT_DIR"/*/; do
        [[ -d "$dir" ]] && generate_readme "${dir%/}"
    done
fi

echo "Done."
