apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: database
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: k3s-vm-fun-bedbug
          containers:
            - name: backup
              image: postgres:16
              command:
                - /bin/bash
                - -c
                - |
                  set -e
                  BACKUP_DIR="/backup"
                  DATE=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="$BACKUP_DIR/pg_dumpall_$DATE.sql.gz"

                  echo "Starting PostgreSQL backup at $(date)"
                  echo "Target: $BACKUP_FILE"

                  # Create backup
                  PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall \
                    -h postgres-postgresql.database.svc.cluster.local \
                    -U postgres \
                    | gzip > "$BACKUP_FILE"

                  # Verify backup
                  if [ -s "$BACKUP_FILE" ]; then
                    SIZE=$(ls -lh "$BACKUP_FILE" | awk '{print $5}')
                    echo "✓ Backup created: $BACKUP_FILE ($SIZE)"
                  else
                    echo "ERROR: Backup file is empty"
                    exit 1
                  fi

                  # Cleanup old backups (keep last 7 days)
                  echo "Cleaning up old backups..."
                  find "$BACKUP_DIR" -name "pg_dumpall_*.sql.gz" -mtime +7 -delete

                  # List current backups
                  echo "Current backups:"
                  ls -lh "$BACKUP_DIR"/*.sql.gz 2>/dev/null || echo "No backups found"

                  echo "Backup completed at $(date)"
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: postgres-password
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: postgres-backup
