# Package Detection Automation for Home Assistant
# Triggers on person detection, uses LLM Vision to confirm package delivery
#
# PREREQUISITES:
# - Frigate 0.16+ with person detection enabled
# - LLM Vision integration with Ollama provider configured
# - llava:7b model pulled to Ollama
#
# ENTITIES TO UPDATE when Frigate 0.16 is ready:
# - binary_sensor.CAMERA_NAME_person_occupancy (person detection trigger)
# - image.CAMERA_NAME_person (person snapshot for analysis)
# - camera.CAMERA_NAME (for zone reference)
#
# Current placeholders use: reolink_doorbell

alias: Package Delivery Detection
description: >-
  Detects package deliveries using person detection + LLM Vision confirmation.
  Notifies via phone push and pulses Voice PE LED.
mode: single
max_exceeded: silent

trigger:
  # Option 1: Reolink native person detection (works without Frigate)
  - platform: state
    entity_id: binary_sensor.reolink_video_doorbell_wifi_person
    from: "off"
    to: "on"
    id: reolink_person

  # Option 2: Frigate person detection (use when 0.16 ready)
  # - platform: state
  #   entity_id: binary_sensor.reolink_doorbell_person_occupancy
  #   from: "off"
  #   to: "on"
  #   id: frigate_person

condition:
  # Only during likely delivery hours (configurable)
  - condition: time
    after: "08:00:00"
    before: "21:00:00"

  # Cooldown: Don't re-trigger within 30 minutes
  - condition: template
    value_template: >-
      {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.package_delivery_detection', 'last_triggered') or 0)) > 1800 }}

action:
  # Step 1: IMMEDIATELY capture snapshot when person detected
  # No delay - catch them while they're still in frame
  - service: camera.snapshot
    target:
      entity_id: camera.reolink_doorbell
    data:
      filename: /config/www/tmp/doorbell_snapshot.jpg

  # Step 2: Analyze snapshot with LLM Vision
  - service: llmvision.image_analyzer
    data:
      provider: 01K1KDVH6Y1GMJ69MJF77WGJEA  # Ollama provider entry_id
      model: llava:7b
      image_file: /config/www/tmp/doorbell_snapshot.jpg
      message: >-
        Analyze this doorbell camera image. Answer ONLY "YES" or "NO":
        Is there a package, box, parcel, or delivery item visible on the porch,
        at the door, or being held by a person?
        Do not consider people, vehicles, bags, or pets as packages.
      max_tokens: 50
      target_width: 1280
    response_variable: llm_response

  # Option B: Use Frigate snapshot (uncomment when 0.16 ready)
  # - service: llmvision.image_analyzer
  #   data:
  #     provider: 01K1KDVH6Y1GMJ69MJF77WGJEA
  #     model: llava:7b
  #     image_entity: image.reolink_doorbell_person
  #     message: "Answer ONLY YES or NO: Is there a package visible?"
  #     max_tokens: 10
  #   response_variable: llm_response

  # Step 3: Log the response for debugging
  - service: logbook.log
    data:
      name: Package Detection
      message: "LLM Vision response: {{ llm_response.response_text }}"
      entity_id: camera.reolink_doorbell

  # Step 4: Check if package detected
  - condition: template
    value_template: >-
      {{ 'yes' in (llm_response.response_text | default('') | lower) }}

  # Step 5: Package confirmed - notify!
  - parallel:
      # Phone notification with image
      - service: notify.mobile_app_pixel_10_pro
        data:
          title: "📦 Package Delivered!"
          message: "A package was detected at your front door."
          data:
            image: /api/camera_proxy/camera.reolink_doorbell
            tag: package_delivery
            channel: Package Alerts
            importance: high
            actions:
              - action: VIEW_CAMERA
                title: View Camera

      # Voice PE LED pulse (blue for 30 seconds)
      - service: light.turn_on
        target:
          entity_id: light.home_assistant_voice_09f5a3_led_ring
        data:
          rgb_color: [0, 100, 255]
          brightness: 200
          effect: pulse

      # Optional: Voice announcement
      # - service: assist_satellite.announce
      #   target:
      #     entity_id: assist_satellite.home_assistant_voice_09f5a3_assist_satellite
      #   data:
      #     message: "A package has been delivered to your front door."

  # Step 6: Reset LED after 30 seconds
  - delay:
      seconds: 30
  - service: light.turn_off
    target:
      entity_id: light.home_assistant_voice_09f5a3_led_ring
