apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: tailscale-operator
      version: "1.78.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    # OAuth credentials referenced from manually-created secret
    oauth:
      clientIdSecretName: "operator-oauth"
      clientIdSecretKey: "client_id"
      clientSecretSecretName: "operator-oauth"
      clientSecretSecretKey: "client_secret"

    # Operator configuration
    operatorConfig:
      hostname: "ts-k8s-operator"
      logging: "info"

    # Enable API server proxy (optional, for secure kubectl)
    apiServerProxyConfig:
      mode: "false"
