apiVersion: batch/v1
kind: CronJob
metadata:
  name: nut-disaster-drill
  namespace: monitoring
spec:
  # Run on the first Saturday of each month at 10:00 AM
  schedule: "0 10 1-7 * 6"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            app: nut-disaster-drill
        spec:
          restartPolicy: Never
          containers:
            - name: drill
              image: dtzar/helm-kubectl:3.14
              command:
                - /bin/bash
                - -c
                - |
                  echo "=== Monthly UPS Disaster Drill ==="
                  echo "Date: $(date)"
                  echo ""

                  PVE_HOST="192.168.4.122"
                  SSH_KEY="/ssh/id_rsa"
                  SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 -i $SSH_KEY"

                  # Test SMS from pve (which has the hotspot fallback configured)
                  echo "Testing SMS Gateway from pve..."
                  ssh $SSH_OPTS root@$PVE_HOST "source /root/.sms-gateway-env && \
                    curl -s -w '\n%{http_code}' -X POST \"http://\${SMS_GATEWAY_IP}:\${SMS_GATEWAY_PORT}/\" \
                    -H \"Authorization: \${SMS_GATEWAY_TOKEN}\" \
                    -H 'Content-Type: application/json' \
                    -d '{\"to\": \"'\${SMS_RECIPIENT}'\", \"message\": \"[DRILL] Monthly UPS disaster drill - '\$(date '+%Y-%m-%d %H:%M')'. SMS notifications working.\"}' \
                    --connect-timeout 10 --max-time 15" > /tmp/result.txt 2>&1

                  http_code=$(tail -1 /tmp/result.txt)
                  cat /tmp/result.txt

                  if [ "$http_code" = "200" ] || [ "$http_code" = "204" ]; then
                    echo ""
                    echo "SMS Gateway: OK (HTTP $http_code)"
                    echo "Drill complete. Check your phone for the test SMS."
                    exit 0
                  else
                    echo ""
                    echo "SMS Gateway: FAILED (HTTP $http_code)"
                    echo "DRILL FAILED - Check Pixel 7 hotspot and SMS Gateway app!"
                    exit 1
                  fi
              volumeMounts:
                - name: ssh-key
                  mountPath: /ssh
                  readOnly: true
          volumes:
            - name: ssh-key
              secret:
                secretName: nut-deploy-ssh-key
                defaultMode: 0600
