apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app: nut-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9199
      targetPort: 9199
      protocol: TCP
      name: metrics
---
# Endpoints pointing to pve's nut_exporter
apiVersion: v1
kind: Endpoints
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app: nut-exporter
subsets:
  - addresses:
      - ip: 192.168.4.122  # pve
    ports:
      - port: 9199
        name: metrics
