name: BalenaCloud Push

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - master

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena Deploy
        uses: bekriebel/balena-cli-action@v1.0.1
        with:
          api-token: ${{secrets.BALENA_API_TOKEN}}
          application-name: ${{secrets.BALENA_APPLICATION_NAME}}
