name: BalenaCloud Push

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - master

jobs:
  balena_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push
        working-directory: ./
        run: |
           curl -L -o /tmp/balena.zip https://github.com/balena-io/balena-cli/releases/download/v11.28.5/balena-cli-v11.28.5-linux-x64-standalone.zip
           unzip /tmp/balena.zip -d /opt
           rm /tmp/balena.zip
           echo "working directory ls"
           ls -R
           echo "changing to root directory"
           cd /
           ls -R
           export PATH=$PATH:/opt/balena-cli
           balena login --token ${{secrets.BALENA_API_TOKEN}}
           echo "balena login completed"
           echo "running balena push ${{secrets.BALENA_APPLICATION_NAME}}"
           balena push ${{secrets.BALENA_APPLICATION_NAME}}
           echo "${{secrets.BALENA_APPLICATION_NAME}} push complete"
